/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ElderRouteImport } from './routes/elder'
import { Route as CarerRouteImport } from './routes/carer'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as CarerIndexRouteImport } from './routes/carer.index'
import { Route as SettingsTextSizeRouteImport } from './routes/settings.text-size'
import { Route as SettingsAppearanceRouteImport } from './routes/settings.appearance'
import { Route as CarerSettingsRouteImport } from './routes/carer.settings'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ElderRoute = ElderRouteImport.update({
  id: '/elder',
  path: '/elder',
  getParentRoute: () => rootRouteImport,
} as any)
const CarerRoute = CarerRouteImport.update({
  id: '/carer',
  path: '/carer',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const CarerIndexRoute = CarerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CarerRoute,
} as any)
const SettingsTextSizeRoute = SettingsTextSizeRouteImport.update({
  id: '/text-size',
  path: '/text-size',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAppearanceRoute = SettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => SettingsRoute,
} as any)
const CarerSettingsRoute = CarerSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => CarerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/carer': typeof CarerRouteWithChildren
  '/elder': typeof ElderRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRouteWithChildren
  '/setup': typeof SetupRoute
  '/carer/settings': typeof CarerSettingsRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/text-size': typeof SettingsTextSizeRoute
  '/carer/': typeof CarerIndexRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/elder': typeof ElderRoute
  '/onboarding': typeof OnboardingRoute
  '/setup': typeof SetupRoute
  '/carer/settings': typeof CarerSettingsRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/text-size': typeof SettingsTextSizeRoute
  '/carer': typeof CarerIndexRoute
  '/settings': typeof SettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/carer': typeof CarerRouteWithChildren
  '/elder': typeof ElderRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRouteWithChildren
  '/setup': typeof SetupRoute
  '/carer/settings': typeof CarerSettingsRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/text-size': typeof SettingsTextSizeRoute
  '/carer/': typeof CarerIndexRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/carer'
    | '/elder'
    | '/onboarding'
    | '/settings'
    | '/setup'
    | '/carer/settings'
    | '/settings/appearance'
    | '/settings/text-size'
    | '/carer/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/elder'
    | '/onboarding'
    | '/setup'
    | '/carer/settings'
    | '/settings/appearance'
    | '/settings/text-size'
    | '/carer'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/carer'
    | '/elder'
    | '/onboarding'
    | '/settings'
    | '/setup'
    | '/carer/settings'
    | '/settings/appearance'
    | '/settings/text-size'
    | '/carer/'
    | '/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CarerRoute: typeof CarerRouteWithChildren
  ElderRoute: typeof ElderRoute
  OnboardingRoute: typeof OnboardingRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elder': {
      id: '/elder'
      path: '/elder'
      fullPath: '/elder'
      preLoaderRoute: typeof ElderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carer': {
      id: '/carer'
      path: '/carer'
      fullPath: '/carer'
      preLoaderRoute: typeof CarerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/carer/': {
      id: '/carer/'
      path: '/'
      fullPath: '/carer/'
      preLoaderRoute: typeof CarerIndexRouteImport
      parentRoute: typeof CarerRoute
    }
    '/settings/text-size': {
      id: '/settings/text-size'
      path: '/text-size'
      fullPath: '/settings/text-size'
      preLoaderRoute: typeof SettingsTextSizeRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/appearance': {
      id: '/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof SettingsAppearanceRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/carer/settings': {
      id: '/carer/settings'
      path: '/settings'
      fullPath: '/carer/settings'
      preLoaderRoute: typeof CarerSettingsRouteImport
      parentRoute: typeof CarerRoute
    }
  }
}

interface CarerRouteChildren {
  CarerSettingsRoute: typeof CarerSettingsRoute
  CarerIndexRoute: typeof CarerIndexRoute
}

const CarerRouteChildren: CarerRouteChildren = {
  CarerSettingsRoute: CarerSettingsRoute,
  CarerIndexRoute: CarerIndexRoute,
}

const CarerRouteWithChildren = CarerRoute._addFileChildren(CarerRouteChildren)

interface SettingsRouteChildren {
  SettingsAppearanceRoute: typeof SettingsAppearanceRoute
  SettingsTextSizeRoute: typeof SettingsTextSizeRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAppearanceRoute: SettingsAppearanceRoute,
  SettingsTextSizeRoute: SettingsTextSizeRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CarerRoute: CarerRouteWithChildren,
  ElderRoute: ElderRoute,
  OnboardingRoute: OnboardingRoute,
  SettingsRoute: SettingsRouteWithChildren,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
